name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  ci_cd_workflow:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository to ensure package.json is available
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Step 3: Install dependencies using npm ci
    - name: Install dependencies
      run: npm ci

    # Step 4: Install Playwright Browsers
    - name: Install Playwright Browsers
      run: npm run install:browsers

    # Step 5: Run MCP tests
    - name: Run MCP Tests
      run: npm run test:mcp

    # Optional: Add success message after tests
    - name: Send success message
      run: echo "CI/CD workflow executed successfully! Hello ${{ inputs.name }}"
